name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Huh
      run: ls -l
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./ConsoleApp1/ConsoleApp1.sln
    - name: Build
      run: dotnet build ./ConsoleApp1/ConsoleApp1.sln --no-restore
    - name: Test
      run: dotnet test ./ConsoleApp1/ConsoleApp1.sln --no-build --verbosity normal
    
